### ISSUE TITLE
Reassignment to console.log?

### ISSUE THREAD

**Issue by 1-max-1** [Jezorko/lambda-simulator#29]
https://github.com/Jezorko/lambda-simulator/blob/b042ead48f831bb356e71df556aa171d9cc84148/src/main/LambdaSimulator.js#L129

Why is `console.log` being overwritten with a new function?

**Comment by Jezorko** [comment]
The [wrapper function](https://github.com/Jezorko/lambda-simulator/blob/b042ead48f831bb356e71df556aa171d9cc84148/src/main/LambdaSimulator.js#L129-L138) is used to capture the logs so they can be [sent as a response header](https://github.com/Jezorko/lambda-simulator/blob/b042ead48f831bb356e71df556aa171d9cc84148/src/main/LambdaSimulator.js#L199) later on. This replicates the response format you'd normally see in AWS.
